# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62989439736cfdaf8c71f653d9b3da9f7b5d4301487c2bad13efe05b87536a7cbfb46f6a7044f6efe209a60da0afd85031c2ce44d23db97f21506581ba7a4c72

test:
  secret_key_base: 75306d617faff2e22d7dcb7ef3eaf0f2d0e02a8c46219a3cb7a3c70d1c9d82c83fef6b213102de9b9b721328075fb9a0fdc3a036c6621efe21430aadad5b77b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
